# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a61a680cfca6ac200a7f14235370c139ab597d5cafda9d9bc53f95fa0fd0c33d46fedf5813ea20bef18c7f7449128080a8b00000329e9205cfbde0c7bf162de8

test:
  secret_key_base: d6fef595babae158897ae5414b26c9521ae544f07d332590a0fd7053fdd403ea6b44f815ae07b5c07dee95f1f3386ddf94ce53ebbbc6090d2eeeba0478a9cae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
